version: '3'

services:
  db:
    image: 'postgres:12.1'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  app:
    depends_on:
      - db
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/sistema-certificado
      - gems:/gems

volumes:
  postgres:
  gems:
